packages:
  - packages/*
  - samples/**

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@workleap*'
  - '@typescript/native-preview'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - netlify-cli
  - sharp
  - unix-dgram
  - unrs-resolver
