packages:
  - packages/*
  - samples/**

# Failing on the CI because "@typescript/native-preview" install binaries packages like "@typescript/native-preview-linux-x64" and
# it seems like "minimumReleaseAgeExclude" only works on "direct" dependencies.
# minimumReleaseAge: 1440
# minimumReleaseAgeExclude:
#   - '@workleap*'
#   - '@typescript/native-preview*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - agent-browser
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - netlify-cli
  - sharp
  - unix-dgram
  - unrs-resolver
