packages:
  - packages/*
  - samples/**

minimumReleaseAgeExclude:
  - '@workleap/*'
  - '@typescript/native-preview*'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  agent-browser: true
  core-js: true
  core-js-pure: true
  edgedriver: true
  esbuild: true
  geckodriver: true
  msw: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true
