openapi: 3.0.1
info:
  title: Workleap Web Configs
  description:  A collection of configuration libraries for building web applications at Workleap.
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/wl-web-configs
  x-cortex-tag: service-wl-web-configs
  x-cortex-type: library
  x-cortex-slack:
    channels:
    - name: internal-dev-platform
      notificationsEnabled: true
  x-cortex-owners:
  - name: team-internal-developer-platform-frontend
    type: GROUP
    provider: CORTEX
  x-cortex-link:
  - type: cortex
    url: https://github.com/gsoft-inc/wl-web-configs/blob/main/.cortex/catalog/service-wl-web-configs.yaml
    name: Edit current Cortex entity in GitHub
